"""NLDM Liberty writer for the optimized SKY130-calibrated cells.

The emitted ``.lib`` is a simplified but structurally valid NLDM subset
(cell delay and output-slew lookup tables vs input slew and output load).
It is intended for the in-tree Python STA; OpenSTA can ingest the same
file after a unit-header tweak if desired.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List

import numpy as np

from dic_mlopt import config as C
from dic_mlopt.physics.cells import CELLS
from dic_mlopt.physics.characterize import CellCharacterizer


SLEWS_NS = np.array([0.01, 0.03, 0.06, 0.12, 0.25])   # ns
LOADS_PF = np.array([0.001, 0.003, 0.006, 0.012, 0.025])  # pF  (= 1..25 fF)


def nldm_tables(char: CellCharacterizer, cell_name: str, wn: float, wp: float,
                corner: str, vdd: float, temp_c: float) -> dict:
    cell = CELLS[cell_name]
    nr, nc = len(SLEWS_NS), len(LOADS_PF)
    rise = np.zeros((nr, nc))
    fall = np.zeros((nr, nc))
    sr = np.zeros((nr, nc))
    sf = np.zeros((nr, nc))
    leak = 0.0
    area = 0.0
    cin = 0.0
    tsu = 0.0
    tcq = 0.0
    th = 0.0
    for i, sl_ns in enumerate(SLEWS_NS):
        for j, cl_pf in enumerate(LOADS_PF):
            r = char.characterize(
                cell, wn, wp, C.LMIN_UM, vdd, temp_c,
                cload_ff=cl_pf * 1000.0, slew_ps=sl_ns * 1000.0, corner=corner,
            )
            rise[i, j] = float(np.mean(r.delay_rise_ps)) / 1000.0  # ns
            fall[i, j] = float(np.mean(r.delay_fall_ps)) / 1000.0
            sr[i, j] = float(np.mean(r.slew_out_ps)) / 1000.0
            sf[i, j] = sr[i, j]
            leak = float(np.mean(r.p_leak_nw)) * 1e-3  # uW  (nW * 1e-3)
            area = float(np.mean(r.area_um2))
            cin = float(np.mean(r.cin_ff)) * 1e-3  # pF
            tsu = float(np.mean(r.t_setup_ps)) / 1000.0
            tcq = float(np.mean(r.t_cq_ps)) / 1000.0
            th = float(np.mean(r.t_hold_ps)) / 1000.0
    return {
        "cell_rise": rise, "cell_fall": fall,
        "rise_trans": sr, "fall_trans": sf,
        "leak_uw": leak, "area": area, "cin_pf": cin,
        "t_setup_ns": tsu, "t_cq_ns": tcq, "t_hold_ns": th,
    }


def _fmt_table(mat: np.ndarray) -> str:
    lines = []
    for row in mat:
        inner = ", ".join(f"{v:.6f}" for v in row)
        lines.append(f'            "{inner}"')
    return ", \\\n".join(lines)


def _index_str(arr: np.ndarray) -> str:
    return ", ".join(f"{v:.4f}" for v in arr)


def write_liberty(sizing: Dict[str, dict], out_path: Path,
                  corner: str = "tt", vdd: float = C.VDD_NOM, temp_c: float = 25.0) -> Path:
    char = CellCharacterizer()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    libname = f"dic_mlopt_sky130_{corner}_{int(vdd*100)}_{int(temp_c)}"
    chunks: List[str] = []
    chunks.append(f"""/* Generated by dic_mlopt — SKY130-calibrated NLDM, corner={corner} */
library ({libname}) {{
  delay_model : table_lookup;
  time_unit : 1ns;
  voltage_unit : 1V;
  current_unit : 1mA;
  pulling_resistance_unit : 1kohm;
  leakage_power_unit : 1uW;
  capacitive_load_unit (1, pf);
  nom_process : 1.0;
  nom_temperature : {temp_c:.1f};
  nom_voltage : {vdd:.3f};
  operating_conditions ({corner}) {{
    process : 1.0;
    temperature : {temp_c:.1f};
    voltage : {vdd:.3f};
  }}
  default_operating_conditions : {corner};

  lu_table_template (delay_5x5) {{
    variable_1 : input_net_transition;
    variable_2 : total_output_net_capacitance;
    index_1 ("{_index_str(SLEWS_NS)}");
    index_2 ("{_index_str(LOADS_PF)}");
  }}
""")
    pin_names = {
        "INV": ("A", "Y"),
        "NAND2": ("A B", "Y"),
        "NOR2": ("A B", "Y"),
        "AOI21": ("A1 A2 B", "Y"),
        "OAI21": ("A1 A2 B", "Y"),
        "MUX2": ("A B S", "Y"),
        "XOR2": ("A B", "Y"),
        "DFF": ("D CLK", "Q"),
    }
    for cname, sz in sizing.items():
        wn, wp = sz["wn_um"], sz["wp_um"]
        t = nldm_tables(char, cname, wn, wp, corner, vdd, temp_c)
        ins, out = pin_names[cname]
        in_list = ins.split()
        cell_id = f"{cname}_X1"
        chunks.append(f"  cell ({cell_id}) {{\n    area : {t['area']:.4f};\n    cell_leakage_power : {t['leak_uw']:.6f};\n")
        for p in in_list:
            cap = t["cin_pf"] / max(len(in_list), 1)
            direction = "input"
            chunks.append(f"    pin ({p}) {{\n      direction : {direction};\n      capacitance : {cap:.6f};\n    }}\n")
        if cname != "DFF":
            chunks.append(f"""    pin ({out}) {{
      direction : output;
      function : "{_function(cname)}";
      timing () {{
        related_pin : "{in_list[0]}";
        timing_sense : {_sense(cname)};
        cell_rise (delay_5x5) {{
          values ( \\
{_fmt_table(t['cell_rise'])}
          );
        }}
        cell_fall (delay_5x5) {{
          values ( \\
{_fmt_table(t['cell_fall'])}
          );
        }}
        rise_transition (delay_5x5) {{
          values ( \\
{_fmt_table(t['rise_trans'])}
          );
        }}
        fall_transition (delay_5x5) {{
          values ( \\
{_fmt_table(t['fall_trans'])}
          );
        }}
      }}
    }}
  }}
""")
        else:
            chunks.append(f"""    ff (IQ, IQN) {{
      next_state : "D";
      clocked_on : "CLK";
    }}
    pin (Q) {{
      direction : output;
      function : "IQ";
      timing () {{
        related_pin : "CLK";
        timing_type : rising_edge;
        cell_rise (delay_5x5) {{
          values ( \\
{_fmt_table(t['cell_rise'])}
          );
        }}
        cell_fall (delay_5x5) {{
          values ( \\
{_fmt_table(t['cell_fall'])}
          );
        }}
        rise_transition (delay_5x5) {{
          values ( \\
{_fmt_table(t['rise_trans'])}
          );
        }}
        fall_transition (delay_5x5) {{
          values ( \\
{_fmt_table(t['fall_trans'])}
          );
        }}
      }}
    }}
    pin (D) {{
      direction : input;
      capacitance : {t['cin_pf']/2:.6f};
      timing () {{
        related_pin : "CLK";
        timing_type : setup_rising;
        rise_constraint (delay_5x5) {{
          values ( \\
{_fmt_table(np.full_like(t['cell_rise'], t['t_setup_ns']))}
          );
        }}
        fall_constraint (delay_5x5) {{
          values ( \\
{_fmt_table(np.full_like(t['cell_fall'], t['t_setup_ns']))}
          );
        }}
      }}
      timing () {{
        related_pin : "CLK";
        timing_type : hold_rising;
        rise_constraint (delay_5x5) {{
          values ( \\
{_fmt_table(np.full_like(t['cell_rise'], t['t_hold_ns']))}
          );
        }}
        fall_constraint (delay_5x5) {{
          values ( \\
{_fmt_table(np.full_like(t['cell_fall'], t['t_hold_ns']))}
          );
        }}
      }}
    }}
  }}
""")
    chunks.append("}\n")
    out_path.write_text("".join(chunks), encoding="utf-8")
    return out_path


def _function(name: str) -> str:
    return {
        "INV": "!A",
        "NAND2": "!(A*B)",
        "NOR2": "!(A+B)",
        "AOI21": "!((A1*A2)+B)",
        "OAI21": "!((A1+A2)*B)",
        "MUX2": "(A*!S)+(B*S)",
        "XOR2": "A^B",
    }[name]


def _sense(name: str) -> str:
    if name in ("INV", "NAND2", "NOR2", "AOI21", "OAI21"):
        return "negative_unate"
    if name in ("MUX2", "XOR2"):
        return "non_unate"
    return "positive_unate"
