"""
Structural Verilog emitter.
===========================

Writes FabAware-Opt's in-memory netlist out as a gate-level Verilog file whose
cell names carry the drive strength the optimizer chose (``NAND2_X2`` rather
than a bare ``NAND2``). Paired with the generated Liberty file this is a
complete, self-consistent input to a real static timing engine:

    netlist.v  +  fabaware_28nm.lib  +  fab32.sdc   ->   sta

The point of this module is that the *optimized* configuration and the
*baseline* configuration become two ordinary gate-level netlists that any
third-party tool can consume, so the improvement can be verified by OpenSTA
instead of by our own arithmetic alone.
"""

from __future__ import annotations

import os
import re
from typing import Dict

from ..design import Netlist
from ..pd import Trial
from .liberty import DRIVES, cell_name_for

CLOCK_NET = "clk"

_BAD = re.compile(r"[^A-Za-z0-9_]")


def sanitize(net: str) -> str:
    """Make a net name safe for Verilog (Yosys emits names like ``_317_``)."""
    name = net.strip().lstrip("\\")
    name = _BAD.sub("_", name)
    if not name or name[0].isdigit():
        name = "n_" + name
    return name


def snap_drive(drive: float, drives=DRIVES) -> float:
    """Round a continuous drive strength onto the nearest available cell."""
    return min(drives, key=lambda d: abs(d - float(drive)))


def cell_instance_name(nl: Netlist, inst, trial: Trial) -> str:
    """Map an instance + trial to a Liberty cell name."""
    if inst.is_dff:
        return "DFF_X1"
    drive = trial.drives.get(inst.cell, 1.0)
    return cell_name_for(inst.cell, snap_drive(drive))


def write_netlist(nl: Netlist, trial: Trial, path: str,
                  module: str = "fab32") -> str:
    """Write a gate-level Verilog netlist for ``nl`` under configuration ``trial``."""
    os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)

    # stable rename so that every net is a legal identifier and collisions are gone
    rename: Dict[str, str] = {}
    used = set()

    def nm(net: str) -> str:
        if net not in rename:
            base = sanitize(net)
            cand, k = base, 0
            while cand in used:
                k += 1
                cand = f"{base}_{k}"
            used.add(cand)
            rename[net] = cand
        return rename[net]

    # 1. reserve the primary I/O first so their names stay recognisable
    for p in list(nl.primary_inputs) + list(nl.primary_outputs):
        nm(p)
    # 2. then every net touched by an instance, so the map is complete
    for inst in nl.instances:
        for net in inst.in_nets:
            nm(net)
        if inst.out_net:
            nm(inst.out_net)
        if inst.is_dff:
            nm(nl.dff_q_of[inst.idx])
    nm(CLOCK_NET)

    pi_names = [nm(p) for p in nl.primary_inputs]
    po_names = [nm(p) for p in nl.primary_outputs]
    # DFF_Q nets may double as primary outputs - keep the port list unique
    po_names = [p for i, p in enumerate(po_names) if p not in po_names[:i]]

    inputs = list(dict.fromkeys(pi_names + (
        [] if CLOCK_NET in pi_names else [CLOCK_NET])))

    L = []
    w = L.append
    w("/* Generated by FabAware-Opt - gate-level netlist for static timing. */")
    w(f"module {module} ( {', '.join(inputs + po_names)} ) ;")
    for p in inputs:
        w(f"  input {p} ;")
    for p in po_names:
        w(f"  output {p} ;")

    # a wire is any net that is neither a declared input nor a declared output
    wire_nets = sorted(set(rename.values()) - set(inputs) - set(po_names))
    if wire_nets:
        w("  wire " + ", ".join(wire_nets) + " ;")
    w("")

    n_gate = 0
    for inst in nl.instances:
        if inst.is_dff:
            d_net = nm(inst.in_nets[0])
            q_net = nm(nl.dff_q_of[inst.idx])
            w(f"  DFF_X1 u_dff{inst.idx} ( "
              f".D({d_net}), .CLK({CLOCK_NET}), .Q({q_net}) ) ;")
        else:
            cell = cell_instance_name(nl, inst, trial)
            conns = ".Y({})".format(nm(inst.out_net))
            for pin, net in zip(_INPUT_PINS(inst.cell), inst.in_nets):
                conns += f", .{pin}({nm(net)})"
            w(f"  {cell} u_{n_gate} ( {conns} ) ;")
            n_gate += 1
    w("")
    w("endmodule")

    with open(path, "w") as f:
        f.write("\n".join(L) + "\n")
    return path


def _INPUT_PINS(cell: str):
    from .liberty import PINS
    return PINS.get(cell, ["A", "B"])
