"""
Liberty (.lib) writer — a virtual PDK for FabAware-Opt.
=======================================================

Real static timing analysis needs a **Liberty** file describing each standard
cell: its function, input capacitance, area, leakage, and delay as a function
of load and input slew. Commercial flows get this from the foundry. We have no
PDK, so we *generate* one from our standard-cell library and compact model.

This is a legitimate thing to do — it is what a "virtual PDK" or an early
(pre-silicon) timing model is. It is also honest: the numbers inside are
predictions of our model, not measurements of silicon. Supply a real PDK
(``--liberty sky130.lib``) and this file is bypassed entirely.

Delay model
-----------
We emit NLDM (non-linear delay model) tables. For each timing arc the delay
is sampled over a load axis using our gate equation

    t = (A + B * C_load) / S

where S is the drive factor from the compact model. A 1-D table over load is
used with a single nominal input slew, which is the minimum OpenSTA accepts.
"""

from __future__ import annotations

import os
from typing import Dict, List, Sequence

from ..library import LIBRARY, area_of, cin_of, leakage_of

#: load axis for the NLDM tables (fF)
LOAD_AXIS: Sequence[float] = (0.5, 1.0, 2.0, 4.0, 8.0, 16.0, 32.0, 64.0)
#: output transition axis (ps) - kept coarse, one nominal slew
SLEW: float = 10.0

#: logic function per cell type (Liberty syntax)
FUNCTIONS: Dict[str, str] = {
    "INV":   "A'",
    "BUF":   "A",
    "NAND2": "(A*B)'",
    "NAND3": "(A*B*C)'",
    "NOR2":  "(A+B)'",
    "XOR2":  "(A^B)",
    "MUX2":  "((S*B)+(S'*A))",
    "A21":   "((A*B)+C)",
    "AOI22": "(((A*B)+(C*D))')",
}

#: input pin names per cell type, in the order the library defines them
PINS: Dict[str, List[str]] = {
    "INV":   ["A"],
    "BUF":   ["A"],
    "NAND2": ["A", "B"],
    "NAND3": ["A", "B", "C"],
    "NOR2":  ["A", "B"],
    "XOR2":  ["A", "B"],
    "MUX2":  ["S", "A", "B"],
    "A21":   ["A", "B", "C"],
    "AOI22": ["A", "B", "C", "D"],
}

#: which output is inverting w.r.t. each input
SENSE: Dict[str, str] = {
    "INV":   "negative_unate",
    "BUF":   "positive_unate",
    "NAND2": "negative_unate",
    "NAND3": "negative_unate",
    "NOR2":  "negative_unate",
    "XOR2":  "non_unate",
    "MUX2":  "non_unate",
    "A21":   "positive_unate",
    "AOI22": "negative_unate",
}

DRIVES: Sequence[float] = (1.0, 2.0, 4.0)


def _fmt(values: Sequence[float], nd: int = 5) -> str:
    return ", ".join(f"{v:.{nd}f}" for v in values)


def cell_delays(cell_name: str, drive: float, ratio: float, vdd: float,
                temp_c: float) -> Dict[str, List[float]]:
    """
    Sample rise/fall delay and output transition over the load axis.

    Uses the same gate equation as the internal engine, so the Liberty file
    and the Python engine agree by construction.
    """
    from .. import compact
    from ..sta import _ratio_factor
    cell = LIBRARY[cell_name]
    # Exactly the engine's gate equation, so the Liberty file and the Python
    # engine agree by construction:  t = (a + b*CL) / (drive * ratio_factor)
    s = drive * _ratio_factor(ratio)

    rise, fall, tr, tf = [], [], [], []
    for cl in LOAD_AXIS:
        d = (cell.a + cell.b * cl) / s
        # the pMOS rail is the weaker one, so the rising output is slower
        slow = d / compact.MU_RATIO_P ** 0.35
        rise.append(slow)
        fall.append(d)
        tr.append(0.7 * slow)
        tf.append(0.7 * d)
    return {"cell_rise": rise, "cell_fall": fall,
            "rise_transition": tr, "fall_transition": tf}


def cell_name_for(cell: str, drive: float) -> str:
    """Canonical cell name for a given drive strength."""
    return f"{cell}_X{int(drive)}"


def write_liberty(
    path: str,
    drives: Sequence[float] = DRIVES,
    ratio: float = 1.0,
    vdd: float = 0.80,
    temp_c: float = 25.0,
    library_name: str = "fabaware_28nm",
) -> str:
    """Write a complete Liberty file for the whole cell library."""
    os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
    L: List[str] = []
    w = L.append

    w(f"library({library_name}) {{")
    w("  /* Generated by FabAware-Opt - virtual 28nm PDK. */")
    w("  /* Delay numbers are predictions of the compact model, not silicon. */")
    w("  delay_model : table_lookup ;")
    w("  capacitive_load_unit (1, ff) ;")
    w("  time_unit : \"1ps\" ;")
    w("  voltage_unit : \"1V\" ;")
    w("  current_unit : \"1mA\" ;")
    w("  leakage_power_unit : \"1mW\" ;")
    w("  pulling_resistance_unit : \"1kohm\" ;")
    w("  nominal_process : 1.0 ;")
    w(f"  nominal_voltage : {vdd:.3f} ;")
    w("  nominal_temperature : %.1f ;" % temp_c)
    w("  default_operating_conditions : TT ;")
    w("")
    w("  operating_conditions (TT) {")
    w("    process : 1.0 ;")
    w(f"    voltage : {vdd:.3f} ;")
    w("    temperature : %.1f ;" % temp_c)
    w("  }")
    w("")
    # wireload model so OpenSTA can estimate interconnect
    w("  wire_load (\"fabaware_wl10\") {")
    w("    resistance : 0.0 ;")
    w("    capacitance : 0.0001 ;")
    w("    area : 0.0 ;")
    w("    slope : 0.5 ;")
    w("    fanout_length (1, 1.0) ;")
    w("    fanout_length (2, 2.0) ;")
    w("    fanout_length (4, 4.0) ;")
    w("    fanout_length (8, 7.0) ;")
    w("  }")
    w("")
    w("  lu_table_template (fabaware_delay) {")
    w("    variable_1 : total_output_net_capacitance ;")
    w(f"    index_1 (\"{_fmt(LOAD_AXIS, 2)}\") ;")
    w("  }")
    w("")

    for cell, ref in LIBRARY.items():
        if cell == "DFF":
            continue
        pins = PINS.get(cell, ["A", "B"])
        func = FUNCTIONS.get(cell, "A'")
        for drive in drives:
            w(f"  cell ({cell_name_for(cell, drive)}) {{")
            w(f"    area : {area_of(ref, drive, ratio):.5f} ;")
            w(f"    cell_leakage_power : "
              f"{vdd * leakage_of(ref, drive, ratio) * 1e-6:.8f} ;")
            w(f"    cell_footprint : {cell.lower()} ;")
            for p in pins:
                w(f"    pin ({p}) {{")
                w("      direction : input ;")
                w(f"      capacitance : {cin_of(ref, drive) / max(len(pins),1):.5f} ;")
                w("    }")
            w("    pin (Y) {")
            w("      direction : output ;")
            w(f"      function : \"{func}\" ;")
            w("      max_capacitance : 64.0 ;")
            for p in pins:
                d = cell_delays(cell, drive, ratio, vdd, temp_c)
                w("      timing () {")
                w(f"        related_pin : \"{p}\" ;")
                w(f"        timing_sense : {SENSE.get(cell, 'positive_unate')} ;")
                for key in ("cell_rise", "cell_fall",
                            "rise_transition", "fall_transition"):
                    w(f"        {key} (fabaware_delay) {{")
                    w(f"          values (\"{_fmt(d[key])}\") ;")
                    w("        }")
                w("      }")
            w("    }")
            w("  }")
            w("")

    # ---------------- flip-flop ----------------
    for drive in (1.0,):
        ref = LIBRARY["DFF"]
        w(f"  cell ({cell_name_for('DFF', drive)}) {{")
        w(f"    area : {area_of(ref, drive, ratio):.5f} ;")
        w(f"    cell_leakage_power : "
          f"{vdd * leakage_of(ref, drive, ratio) * 1e-6:.8f} ;")
        w("    ff (\"IQ\", \"IQN\") {")
        w("      next_state : \"D\" ;")
        w("      clocked_on : \"CLK\" ;")
        w("      clear_preset_var1 : L ;")
        w("      clear_preset_var2 : H ;")
        w("    }")
        w("    pin (CLK) {")
        w("      direction : input ;")
        w("      clock : true ;")
        w(f"      capacitance : {cin_of(ref, drive) / 2:.5f} ;")
        w("    }")
        w("    pin (D) {")
        w("      direction : input ;")
        w(f"      capacitance : {cin_of(ref, drive) / 2:.5f} ;")
        w("      timing () {")
        w("        related_pin : \"CLK\" ;")
        w("        timing_type : setup_rising ;")
        w("        rise_constraint (fabaware_delay) {")
        w(f"          values (\"{_fmt([ref.setup] * len(LOAD_AXIS))}\") ;")
        w("        }")
        w("        fall_constraint (fabaware_delay) {")
        w(f"          values (\"{_fmt([ref.setup] * len(LOAD_AXIS))}\") ;")
        w("        }")
        w("      }")
        w("      timing () {")
        w("        related_pin : \"CLK\" ;")
        w("        timing_type : hold_rising ;")
        w("        rise_constraint (fabaware_delay) {")
        w(f"          values (\"{_fmt([0.0] * len(LOAD_AXIS))}\") ;")
        w("        }")
        w("        fall_constraint (fabaware_delay) {")
        w(f"          values (\"{_fmt([0.0] * len(LOAD_AXIS))}\") ;")
        w("        }")
        w("      }")
        w("    }")
        w("    pin (Q) {")
        w("      direction : output ;")
        w("      function : \"IQ\" ;")
        w("      timing () {")
        w("        related_pin : \"CLK\" ;")
        w("        timing_type : rising_edge ;")
        d = cell_delays("BUF", drive, ratio, vdd, temp_c)
        for key in ("cell_rise", "cell_fall",
                    "rise_transition", "fall_transition"):
            w(f"        {key} (fabaware_delay) {{")
            w(f"          values (\"{_fmt([x + 25.0 for x in d[key]])}\") ;")
            w("        }")
        w("      }")
        w("    }")
        w("  }")
        w("")

    w(f"}} /* library {library_name} */")
    w("")

    text = "\n".join(L)
    with open(path, "w") as f:
        f.write(text)
    return path
